services:
  postgres:
    image: postgres:16-alpine
    container_name: hrms-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hrms
      POSTGRES_PASSWORD: hrms_secret
      POSTGRES_DB: hrms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
